package com.yjkj.ks_user.mapper;

import com.yjkj.ks_user.entity.KSAgentRateTable;
import com.yjkj.ks_user.entity.KSAgentRateTableExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KSAgentRateTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int countByExample(KSAgentRateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int deleteByExample(KSAgentRateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int insert(KSAgentRateTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int insertSelective(KSAgentRateTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    List<KSAgentRateTable> selectByExample(KSAgentRateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    KSAgentRateTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") KSAgentRateTable record, @Param("example") KSAgentRateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") KSAgentRateTable record, @Param("example") KSAgentRateTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KSAgentRateTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KSAgentRateTable record);
}