package com.yjkj.ks_user.entity;

import java.util.ArrayList;
import java.util.List;

public class AisleNameExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public AisleNameExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAisleCodeIsNull() {
            addCriterion("aisle_code is null");
            return (Criteria) this;
        }

        public Criteria andAisleCodeIsNotNull() {
            addCriterion("aisle_code is not null");
            return (Criteria) this;
        }

        public Criteria andAisleCodeEqualTo(String value) {
            addCriterion("aisle_code =", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeNotEqualTo(String value) {
            addCriterion("aisle_code <>", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeGreaterThan(String value) {
            addCriterion("aisle_code >", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("aisle_code >=", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeLessThan(String value) {
            addCriterion("aisle_code <", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeLessThanOrEqualTo(String value) {
            addCriterion("aisle_code <=", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeLike(String value) {
            addCriterion("aisle_code like", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeNotLike(String value) {
            addCriterion("aisle_code not like", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeIn(List<String> values) {
            addCriterion("aisle_code in", values, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeNotIn(List<String> values) {
            addCriterion("aisle_code not in", values, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeBetween(String value1, String value2) {
            addCriterion("aisle_code between", value1, value2, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeNotBetween(String value1, String value2) {
            addCriterion("aisle_code not between", value1, value2, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleNameIsNull() {
            addCriterion("aisle_name is null");
            return (Criteria) this;
        }

        public Criteria andAisleNameIsNotNull() {
            addCriterion("aisle_name is not null");
            return (Criteria) this;
        }

        public Criteria andAisleNameEqualTo(String value) {
            addCriterion("aisle_name =", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameNotEqualTo(String value) {
            addCriterion("aisle_name <>", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameGreaterThan(String value) {
            addCriterion("aisle_name >", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameGreaterThanOrEqualTo(String value) {
            addCriterion("aisle_name >=", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameLessThan(String value) {
            addCriterion("aisle_name <", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameLessThanOrEqualTo(String value) {
            addCriterion("aisle_name <=", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameLike(String value) {
            addCriterion("aisle_name like", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameNotLike(String value) {
            addCriterion("aisle_name not like", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameIn(List<String> values) {
            addCriterion("aisle_name in", values, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameNotIn(List<String> values) {
            addCriterion("aisle_name not in", values, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameBetween(String value1, String value2) {
            addCriterion("aisle_name between", value1, value2, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameNotBetween(String value1, String value2) {
            addCriterion("aisle_name not between", value1, value2, "aisleName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aisle_compare_name
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aisle_compare_name
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}