package com.yjkj.ks_user.entity;

public class FixReward {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_fixed_reward.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_fixed_reward.one_Mer
     *
     * @mbggenerated
     */
    private Long oneMer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_fixed_reward.two_Mer
     *
     * @mbggenerated
     */
    private Long twoMer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_fixed_reward.three_Mer
     *
     * @mbggenerated
     */
    private Long threeMer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_fixed_reward.remarks_One
     *
     * @mbggenerated
     */
    private Long remarksOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_fixed_reward.remarks_Two
     *
     * @mbggenerated
     */
    private Long remarksTwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_fixed_reward.id
     *
     * @return the value of ks_fixed_reward.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_fixed_reward.id
     *
     * @param id the value for ks_fixed_reward.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_fixed_reward.one_Mer
     *
     * @return the value of ks_fixed_reward.one_Mer
     *
     * @mbggenerated
     */
    public Long getOneMer() {
        return oneMer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_fixed_reward.one_Mer
     *
     * @param oneMer the value for ks_fixed_reward.one_Mer
     *
     * @mbggenerated
     */
    public void setOneMer(Long oneMer) {
        this.oneMer = oneMer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_fixed_reward.two_Mer
     *
     * @return the value of ks_fixed_reward.two_Mer
     *
     * @mbggenerated
     */
    public Long getTwoMer() {
        return twoMer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_fixed_reward.two_Mer
     *
     * @param twoMer the value for ks_fixed_reward.two_Mer
     *
     * @mbggenerated
     */
    public void setTwoMer(Long twoMer) {
        this.twoMer = twoMer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_fixed_reward.three_Mer
     *
     * @return the value of ks_fixed_reward.three_Mer
     *
     * @mbggenerated
     */
    public Long getThreeMer() {
        return threeMer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_fixed_reward.three_Mer
     *
     * @param threeMer the value for ks_fixed_reward.three_Mer
     *
     * @mbggenerated
     */
    public void setThreeMer(Long threeMer) {
        this.threeMer = threeMer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_fixed_reward.remarks_One
     *
     * @return the value of ks_fixed_reward.remarks_One
     *
     * @mbggenerated
     */
    public Long getRemarksOne() {
        return remarksOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_fixed_reward.remarks_One
     *
     * @param remarksOne the value for ks_fixed_reward.remarks_One
     *
     * @mbggenerated
     */
    public void setRemarksOne(Long remarksOne) {
        this.remarksOne = remarksOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_fixed_reward.remarks_Two
     *
     * @return the value of ks_fixed_reward.remarks_Two
     *
     * @mbggenerated
     */
    public Long getRemarksTwo() {
        return remarksTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_fixed_reward.remarks_Two
     *
     * @param remarksTwo the value for ks_fixed_reward.remarks_Two
     *
     * @mbggenerated
     */
    public void setRemarksTwo(Long remarksTwo) {
        this.remarksTwo = remarksTwo;
    }
}