package com.yjkj.ks_user.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class KSAgentRateTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public KSAgentRateTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAgentLevelIsNull() {
            addCriterion("agent_level is null");
            return (Criteria) this;
        }

        public Criteria andAgentLevelIsNotNull() {
            addCriterion("agent_level is not null");
            return (Criteria) this;
        }

        public Criteria andAgentLevelEqualTo(String value) {
            addCriterion("agent_level =", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelNotEqualTo(String value) {
            addCriterion("agent_level <>", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelGreaterThan(String value) {
            addCriterion("agent_level >", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelGreaterThanOrEqualTo(String value) {
            addCriterion("agent_level >=", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelLessThan(String value) {
            addCriterion("agent_level <", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelLessThanOrEqualTo(String value) {
            addCriterion("agent_level <=", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelLike(String value) {
            addCriterion("agent_level like", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelNotLike(String value) {
            addCriterion("agent_level not like", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelIn(List<String> values) {
            addCriterion("agent_level in", values, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelNotIn(List<String> values) {
            addCriterion("agent_level not in", values, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelBetween(String value1, String value2) {
            addCriterion("agent_level between", value1, value2, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelNotBetween(String value1, String value2) {
            addCriterion("agent_level not between", value1, value2, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("rate is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("rate is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(BigDecimal value) {
            addCriterion("rate =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(BigDecimal value) {
            addCriterion("rate <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(BigDecimal value) {
            addCriterion("rate >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(BigDecimal value) {
            addCriterion("rate <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<BigDecimal> values) {
            addCriterion("rate in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<BigDecimal> values) {
            addCriterion("rate not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate not between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andD0FeeIsNull() {
            addCriterion("d0_fee is null");
            return (Criteria) this;
        }

        public Criteria andD0FeeIsNotNull() {
            addCriterion("d0_fee is not null");
            return (Criteria) this;
        }

        public Criteria andD0FeeEqualTo(Long value) {
            addCriterion("d0_fee =", value, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeNotEqualTo(Long value) {
            addCriterion("d0_fee <>", value, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeGreaterThan(Long value) {
            addCriterion("d0_fee >", value, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeGreaterThanOrEqualTo(Long value) {
            addCriterion("d0_fee >=", value, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeLessThan(Long value) {
            addCriterion("d0_fee <", value, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeLessThanOrEqualTo(Long value) {
            addCriterion("d0_fee <=", value, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeIn(List<Long> values) {
            addCriterion("d0_fee in", values, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeNotIn(List<Long> values) {
            addCriterion("d0_fee not in", values, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeBetween(Long value1, Long value2) {
            addCriterion("d0_fee between", value1, value2, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andD0FeeNotBetween(Long value1, Long value2) {
            addCriterion("d0_fee not between", value1, value2, "d0Fee");
            return (Criteria) this;
        }

        public Criteria andAisleCodeIsNull() {
            addCriterion("aisle_code is null");
            return (Criteria) this;
        }

        public Criteria andAisleCodeIsNotNull() {
            addCriterion("aisle_code is not null");
            return (Criteria) this;
        }

        public Criteria andAisleCodeEqualTo(String value) {
            addCriterion("aisle_code =", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeNotEqualTo(String value) {
            addCriterion("aisle_code <>", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeGreaterThan(String value) {
            addCriterion("aisle_code >", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("aisle_code >=", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeLessThan(String value) {
            addCriterion("aisle_code <", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeLessThanOrEqualTo(String value) {
            addCriterion("aisle_code <=", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeLike(String value) {
            addCriterion("aisle_code like", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeNotLike(String value) {
            addCriterion("aisle_code not like", value, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeIn(List<String> values) {
            addCriterion("aisle_code in", values, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeNotIn(List<String> values) {
            addCriterion("aisle_code not in", values, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeBetween(String value1, String value2) {
            addCriterion("aisle_code between", value1, value2, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleCodeNotBetween(String value1, String value2) {
            addCriterion("aisle_code not between", value1, value2, "aisleCode");
            return (Criteria) this;
        }

        public Criteria andAisleNameIsNull() {
            addCriterion("aisle_name is null");
            return (Criteria) this;
        }

        public Criteria andAisleNameIsNotNull() {
            addCriterion("aisle_name is not null");
            return (Criteria) this;
        }

        public Criteria andAisleNameEqualTo(String value) {
            addCriterion("aisle_name =", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameNotEqualTo(String value) {
            addCriterion("aisle_name <>", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameGreaterThan(String value) {
            addCriterion("aisle_name >", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameGreaterThanOrEqualTo(String value) {
            addCriterion("aisle_name >=", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameLessThan(String value) {
            addCriterion("aisle_name <", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameLessThanOrEqualTo(String value) {
            addCriterion("aisle_name <=", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameLike(String value) {
            addCriterion("aisle_name like", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameNotLike(String value) {
            addCriterion("aisle_name not like", value, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameIn(List<String> values) {
            addCriterion("aisle_name in", values, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameNotIn(List<String> values) {
            addCriterion("aisle_name not in", values, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameBetween(String value1, String value2) {
            addCriterion("aisle_name between", value1, value2, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAisleNameNotBetween(String value1, String value2) {
            addCriterion("aisle_name not between", value1, value2, "aisleName");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andIsLdIsNull() {
            addCriterion("is_ld is null");
            return (Criteria) this;
        }

        public Criteria andIsLdIsNotNull() {
            addCriterion("is_ld is not null");
            return (Criteria) this;
        }

        public Criteria andIsLdEqualTo(String value) {
            addCriterion("is_ld =", value, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdNotEqualTo(String value) {
            addCriterion("is_ld <>", value, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdGreaterThan(String value) {
            addCriterion("is_ld >", value, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdGreaterThanOrEqualTo(String value) {
            addCriterion("is_ld >=", value, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdLessThan(String value) {
            addCriterion("is_ld <", value, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdLessThanOrEqualTo(String value) {
            addCriterion("is_ld <=", value, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdLike(String value) {
            addCriterion("is_ld like", value, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdNotLike(String value) {
            addCriterion("is_ld not like", value, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdIn(List<String> values) {
            addCriterion("is_ld in", values, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdNotIn(List<String> values) {
            addCriterion("is_ld not in", values, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdBetween(String value1, String value2) {
            addCriterion("is_ld between", value1, value2, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsLdNotBetween(String value1, String value2) {
            addCriterion("is_ld not between", value1, value2, "isLd");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentIsNull() {
            addCriterion("is_repayment is null");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentIsNotNull() {
            addCriterion("is_repayment is not null");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentEqualTo(String value) {
            addCriterion("is_repayment =", value, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentNotEqualTo(String value) {
            addCriterion("is_repayment <>", value, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentGreaterThan(String value) {
            addCriterion("is_repayment >", value, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentGreaterThanOrEqualTo(String value) {
            addCriterion("is_repayment >=", value, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentLessThan(String value) {
            addCriterion("is_repayment <", value, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentLessThanOrEqualTo(String value) {
            addCriterion("is_repayment <=", value, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentLike(String value) {
            addCriterion("is_repayment like", value, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentNotLike(String value) {
            addCriterion("is_repayment not like", value, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentIn(List<String> values) {
            addCriterion("is_repayment in", values, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentNotIn(List<String> values) {
            addCriterion("is_repayment not in", values, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentBetween(String value1, String value2) {
            addCriterion("is_repayment between", value1, value2, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andIsRepaymentNotBetween(String value1, String value2) {
            addCriterion("is_repayment not between", value1, value2, "isRepayment");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoIsNull() {
            addCriterion("remarks_two is null");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoIsNotNull() {
            addCriterion("remarks_two is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoEqualTo(String value) {
            addCriterion("remarks_two =", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoNotEqualTo(String value) {
            addCriterion("remarks_two <>", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoGreaterThan(String value) {
            addCriterion("remarks_two >", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoGreaterThanOrEqualTo(String value) {
            addCriterion("remarks_two >=", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoLessThan(String value) {
            addCriterion("remarks_two <", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoLessThanOrEqualTo(String value) {
            addCriterion("remarks_two <=", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoLike(String value) {
            addCriterion("remarks_two like", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoNotLike(String value) {
            addCriterion("remarks_two not like", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoIn(List<String> values) {
            addCriterion("remarks_two in", values, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoNotIn(List<String> values) {
            addCriterion("remarks_two not in", values, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoBetween(String value1, String value2) {
            addCriterion("remarks_two between", value1, value2, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoNotBetween(String value1, String value2) {
            addCriterion("remarks_two not between", value1, value2, "remarksTwo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ks_agent_rate
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ks_agent_rate
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}