package com.yjkj.ks_user.entity;

import java.util.ArrayList;
import java.util.List;

public class PaymentNumExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public PaymentNumExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelIsNull() {
            addCriterion("identity_Level is null");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelIsNotNull() {
            addCriterion("identity_Level is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelEqualTo(String value) {
            addCriterion("identity_Level =", value, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelNotEqualTo(String value) {
            addCriterion("identity_Level <>", value, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelGreaterThan(String value) {
            addCriterion("identity_Level >", value, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelGreaterThanOrEqualTo(String value) {
            addCriterion("identity_Level >=", value, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelLessThan(String value) {
            addCriterion("identity_Level <", value, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelLessThanOrEqualTo(String value) {
            addCriterion("identity_Level <=", value, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelLike(String value) {
            addCriterion("identity_Level like", value, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelNotLike(String value) {
            addCriterion("identity_Level not like", value, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelIn(List<String> values) {
            addCriterion("identity_Level in", values, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelNotIn(List<String> values) {
            addCriterion("identity_Level not in", values, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelBetween(String value1, String value2) {
            addCriterion("identity_Level between", value1, value2, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityLevelNotBetween(String value1, String value2) {
            addCriterion("identity_Level not between", value1, value2, "identityLevel");
            return (Criteria) this;
        }

        public Criteria andIdentityNameIsNull() {
            addCriterion("identity_Name is null");
            return (Criteria) this;
        }

        public Criteria andIdentityNameIsNotNull() {
            addCriterion("identity_Name is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityNameEqualTo(String value) {
            addCriterion("identity_Name =", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameNotEqualTo(String value) {
            addCriterion("identity_Name <>", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameGreaterThan(String value) {
            addCriterion("identity_Name >", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameGreaterThanOrEqualTo(String value) {
            addCriterion("identity_Name >=", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameLessThan(String value) {
            addCriterion("identity_Name <", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameLessThanOrEqualTo(String value) {
            addCriterion("identity_Name <=", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameLike(String value) {
            addCriterion("identity_Name like", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameNotLike(String value) {
            addCriterion("identity_Name not like", value, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameIn(List<String> values) {
            addCriterion("identity_Name in", values, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameNotIn(List<String> values) {
            addCriterion("identity_Name not in", values, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameBetween(String value1, String value2) {
            addCriterion("identity_Name between", value1, value2, "identityName");
            return (Criteria) this;
        }

        public Criteria andIdentityNameNotBetween(String value1, String value2) {
            addCriterion("identity_Name not between", value1, value2, "identityName");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotIsNull() {
            addCriterion("reward_Or_Not is null");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotIsNotNull() {
            addCriterion("reward_Or_Not is not null");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotEqualTo(String value) {
            addCriterion("reward_Or_Not =", value, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotNotEqualTo(String value) {
            addCriterion("reward_Or_Not <>", value, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotGreaterThan(String value) {
            addCriterion("reward_Or_Not >", value, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotGreaterThanOrEqualTo(String value) {
            addCriterion("reward_Or_Not >=", value, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotLessThan(String value) {
            addCriterion("reward_Or_Not <", value, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotLessThanOrEqualTo(String value) {
            addCriterion("reward_Or_Not <=", value, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotLike(String value) {
            addCriterion("reward_Or_Not like", value, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotNotLike(String value) {
            addCriterion("reward_Or_Not not like", value, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotIn(List<String> values) {
            addCriterion("reward_Or_Not in", values, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotNotIn(List<String> values) {
            addCriterion("reward_Or_Not not in", values, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotBetween(String value1, String value2) {
            addCriterion("reward_Or_Not between", value1, value2, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andRewardOrNotNotBetween(String value1, String value2) {
            addCriterion("reward_Or_Not not between", value1, value2, "rewardOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotIsNull() {
            addCriterion("agent_Or_Not is null");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotIsNotNull() {
            addCriterion("agent_Or_Not is not null");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotEqualTo(String value) {
            addCriterion("agent_Or_Not =", value, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotNotEqualTo(String value) {
            addCriterion("agent_Or_Not <>", value, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotGreaterThan(String value) {
            addCriterion("agent_Or_Not >", value, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotGreaterThanOrEqualTo(String value) {
            addCriterion("agent_Or_Not >=", value, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotLessThan(String value) {
            addCriterion("agent_Or_Not <", value, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotLessThanOrEqualTo(String value) {
            addCriterion("agent_Or_Not <=", value, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotLike(String value) {
            addCriterion("agent_Or_Not like", value, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotNotLike(String value) {
            addCriterion("agent_Or_Not not like", value, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotIn(List<String> values) {
            addCriterion("agent_Or_Not in", values, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotNotIn(List<String> values) {
            addCriterion("agent_Or_Not not in", values, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotBetween(String value1, String value2) {
            addCriterion("agent_Or_Not between", value1, value2, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentOrNotNotBetween(String value1, String value2) {
            addCriterion("agent_Or_Not not between", value1, value2, "agentOrNot");
            return (Criteria) this;
        }

        public Criteria andAgentLevelIsNull() {
            addCriterion("agent_Level is null");
            return (Criteria) this;
        }

        public Criteria andAgentLevelIsNotNull() {
            addCriterion("agent_Level is not null");
            return (Criteria) this;
        }

        public Criteria andAgentLevelEqualTo(String value) {
            addCriterion("agent_Level =", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelNotEqualTo(String value) {
            addCriterion("agent_Level <>", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelGreaterThan(String value) {
            addCriterion("agent_Level >", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelGreaterThanOrEqualTo(String value) {
            addCriterion("agent_Level >=", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelLessThan(String value) {
            addCriterion("agent_Level <", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelLessThanOrEqualTo(String value) {
            addCriterion("agent_Level <=", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelLike(String value) {
            addCriterion("agent_Level like", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelNotLike(String value) {
            addCriterion("agent_Level not like", value, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelIn(List<String> values) {
            addCriterion("agent_Level in", values, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelNotIn(List<String> values) {
            addCriterion("agent_Level not in", values, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelBetween(String value1, String value2) {
            addCriterion("agent_Level between", value1, value2, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andAgentLevelNotBetween(String value1, String value2) {
            addCriterion("agent_Level not between", value1, value2, "agentLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelIsNull() {
            addCriterion("mer_Level is null");
            return (Criteria) this;
        }

        public Criteria andMerLevelIsNotNull() {
            addCriterion("mer_Level is not null");
            return (Criteria) this;
        }

        public Criteria andMerLevelEqualTo(String value) {
            addCriterion("mer_Level =", value, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelNotEqualTo(String value) {
            addCriterion("mer_Level <>", value, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelGreaterThan(String value) {
            addCriterion("mer_Level >", value, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelGreaterThanOrEqualTo(String value) {
            addCriterion("mer_Level >=", value, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelLessThan(String value) {
            addCriterion("mer_Level <", value, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelLessThanOrEqualTo(String value) {
            addCriterion("mer_Level <=", value, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelLike(String value) {
            addCriterion("mer_Level like", value, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelNotLike(String value) {
            addCriterion("mer_Level not like", value, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelIn(List<String> values) {
            addCriterion("mer_Level in", values, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelNotIn(List<String> values) {
            addCriterion("mer_Level not in", values, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelBetween(String value1, String value2) {
            addCriterion("mer_Level between", value1, value2, "merLevel");
            return (Criteria) this;
        }

        public Criteria andMerLevelNotBetween(String value1, String value2) {
            addCriterion("mer_Level not between", value1, value2, "merLevel");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityIsNull() {
            addCriterion("payment_Identity is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityIsNotNull() {
            addCriterion("payment_Identity is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityEqualTo(String value) {
            addCriterion("payment_Identity =", value, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityNotEqualTo(String value) {
            addCriterion("payment_Identity <>", value, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityGreaterThan(String value) {
            addCriterion("payment_Identity >", value, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("payment_Identity >=", value, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityLessThan(String value) {
            addCriterion("payment_Identity <", value, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityLessThanOrEqualTo(String value) {
            addCriterion("payment_Identity <=", value, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityLike(String value) {
            addCriterion("payment_Identity like", value, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityNotLike(String value) {
            addCriterion("payment_Identity not like", value, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityIn(List<String> values) {
            addCriterion("payment_Identity in", values, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityNotIn(List<String> values) {
            addCriterion("payment_Identity not in", values, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityBetween(String value1, String value2) {
            addCriterion("payment_Identity between", value1, value2, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentIdentityNotBetween(String value1, String value2) {
            addCriterion("payment_Identity not between", value1, value2, "paymentIdentity");
            return (Criteria) this;
        }

        public Criteria andPaymentNumIsNull() {
            addCriterion("payment_Num is null");
            return (Criteria) this;
        }

        public Criteria andPaymentNumIsNotNull() {
            addCriterion("payment_Num is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentNumEqualTo(Long value) {
            addCriterion("payment_Num =", value, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumNotEqualTo(Long value) {
            addCriterion("payment_Num <>", value, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumGreaterThan(Long value) {
            addCriterion("payment_Num >", value, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumGreaterThanOrEqualTo(Long value) {
            addCriterion("payment_Num >=", value, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumLessThan(Long value) {
            addCriterion("payment_Num <", value, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumLessThanOrEqualTo(Long value) {
            addCriterion("payment_Num <=", value, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumIn(List<Long> values) {
            addCriterion("payment_Num in", values, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumNotIn(List<Long> values) {
            addCriterion("payment_Num not in", values, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumBetween(Long value1, Long value2) {
            addCriterion("payment_Num between", value1, value2, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andPaymentNumNotBetween(Long value1, Long value2) {
            addCriterion("payment_Num not between", value1, value2, "paymentNum");
            return (Criteria) this;
        }

        public Criteria andFixRewardIsNull() {
            addCriterion("fix_Reward is null");
            return (Criteria) this;
        }

        public Criteria andFixRewardIsNotNull() {
            addCriterion("fix_Reward is not null");
            return (Criteria) this;
        }

        public Criteria andFixRewardEqualTo(Long value) {
            addCriterion("fix_Reward =", value, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardNotEqualTo(Long value) {
            addCriterion("fix_Reward <>", value, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardGreaterThan(Long value) {
            addCriterion("fix_Reward >", value, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardGreaterThanOrEqualTo(Long value) {
            addCriterion("fix_Reward >=", value, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardLessThan(Long value) {
            addCriterion("fix_Reward <", value, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardLessThanOrEqualTo(Long value) {
            addCriterion("fix_Reward <=", value, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardIn(List<Long> values) {
            addCriterion("fix_Reward in", values, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardNotIn(List<Long> values) {
            addCriterion("fix_Reward not in", values, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardBetween(Long value1, Long value2) {
            addCriterion("fix_Reward between", value1, value2, "fixReward");
            return (Criteria) this;
        }

        public Criteria andFixRewardNotBetween(Long value1, Long value2) {
            addCriterion("fix_Reward not between", value1, value2, "fixReward");
            return (Criteria) this;
        }

        public Criteria andSubsidyIsNull() {
            addCriterion("subsidy is null");
            return (Criteria) this;
        }

        public Criteria andSubsidyIsNotNull() {
            addCriterion("subsidy is not null");
            return (Criteria) this;
        }

        public Criteria andSubsidyEqualTo(Long value) {
            addCriterion("subsidy =", value, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyNotEqualTo(Long value) {
            addCriterion("subsidy <>", value, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyGreaterThan(Long value) {
            addCriterion("subsidy >", value, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyGreaterThanOrEqualTo(Long value) {
            addCriterion("subsidy >=", value, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyLessThan(Long value) {
            addCriterion("subsidy <", value, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyLessThanOrEqualTo(Long value) {
            addCriterion("subsidy <=", value, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyIn(List<Long> values) {
            addCriterion("subsidy in", values, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyNotIn(List<Long> values) {
            addCriterion("subsidy not in", values, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyBetween(Long value1, Long value2) {
            addCriterion("subsidy between", value1, value2, "subsidy");
            return (Criteria) this;
        }

        public Criteria andSubsidyNotBetween(Long value1, Long value2) {
            addCriterion("subsidy not between", value1, value2, "subsidy");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoIsNull() {
            addCriterion("remarks_Two is null");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoIsNotNull() {
            addCriterion("remarks_Two is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoEqualTo(String value) {
            addCriterion("remarks_Two =", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoNotEqualTo(String value) {
            addCriterion("remarks_Two <>", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoGreaterThan(String value) {
            addCriterion("remarks_Two >", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoGreaterThanOrEqualTo(String value) {
            addCriterion("remarks_Two >=", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoLessThan(String value) {
            addCriterion("remarks_Two <", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoLessThanOrEqualTo(String value) {
            addCriterion("remarks_Two <=", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoLike(String value) {
            addCriterion("remarks_Two like", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoNotLike(String value) {
            addCriterion("remarks_Two not like", value, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoIn(List<String> values) {
            addCriterion("remarks_Two in", values, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoNotIn(List<String> values) {
            addCriterion("remarks_Two not in", values, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoBetween(String value1, String value2) {
            addCriterion("remarks_Two between", value1, value2, "remarksTwo");
            return (Criteria) this;
        }

        public Criteria andRemarksTwoNotBetween(String value1, String value2) {
            addCriterion("remarks_Two not between", value1, value2, "remarksTwo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ks_payment_num
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ks_payment_num
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}