package com.yjkj.ks_user.entity;

public class PaymentNum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.identity_Level
     *
     * @mbggenerated
     */
    private String identityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.identity_Name
     *
     * @mbggenerated
     */
    private String identityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.reward_Or_Not
     *
     * @mbggenerated
     */
    private String rewardOrNot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.agent_Or_Not
     *
     * @mbggenerated
     */
    private String agentOrNot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.agent_Level
     *
     * @mbggenerated
     */
    private String agentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.mer_Level
     *
     * @mbggenerated
     */
    private String merLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.payment_Identity
     *
     * @mbggenerated
     */
    private String paymentIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.payment_Num
     *
     * @mbggenerated
     */
    private Long paymentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.fix_Reward
     *
     * @mbggenerated
     */
    private Long fixReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.subsidy
     *
     * @mbggenerated
     */
    private Long subsidy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ks_payment_num.remarks_Two
     *
     * @mbggenerated
     */
    private String remarksTwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.id
     *
     * @return the value of ks_payment_num.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.id
     *
     * @param id the value for ks_payment_num.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.identity_Level
     *
     * @return the value of ks_payment_num.identity_Level
     *
     * @mbggenerated
     */
    public String getIdentityLevel() {
        return identityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.identity_Level
     *
     * @param identityLevel the value for ks_payment_num.identity_Level
     *
     * @mbggenerated
     */
    public void setIdentityLevel(String identityLevel) {
        this.identityLevel = identityLevel == null ? null : identityLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.identity_Name
     *
     * @return the value of ks_payment_num.identity_Name
     *
     * @mbggenerated
     */
    public String getIdentityName() {
        return identityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.identity_Name
     *
     * @param identityName the value for ks_payment_num.identity_Name
     *
     * @mbggenerated
     */
    public void setIdentityName(String identityName) {
        this.identityName = identityName == null ? null : identityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.reward_Or_Not
     *
     * @return the value of ks_payment_num.reward_Or_Not
     *
     * @mbggenerated
     */
    public String getRewardOrNot() {
        return rewardOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.reward_Or_Not
     *
     * @param rewardOrNot the value for ks_payment_num.reward_Or_Not
     *
     * @mbggenerated
     */
    public void setRewardOrNot(String rewardOrNot) {
        this.rewardOrNot = rewardOrNot == null ? null : rewardOrNot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.agent_Or_Not
     *
     * @return the value of ks_payment_num.agent_Or_Not
     *
     * @mbggenerated
     */
    public String getAgentOrNot() {
        return agentOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.agent_Or_Not
     *
     * @param agentOrNot the value for ks_payment_num.agent_Or_Not
     *
     * @mbggenerated
     */
    public void setAgentOrNot(String agentOrNot) {
        this.agentOrNot = agentOrNot == null ? null : agentOrNot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.agent_Level
     *
     * @return the value of ks_payment_num.agent_Level
     *
     * @mbggenerated
     */
    public String getAgentLevel() {
        return agentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.agent_Level
     *
     * @param agentLevel the value for ks_payment_num.agent_Level
     *
     * @mbggenerated
     */
    public void setAgentLevel(String agentLevel) {
        this.agentLevel = agentLevel == null ? null : agentLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.mer_Level
     *
     * @return the value of ks_payment_num.mer_Level
     *
     * @mbggenerated
     */
    public String getMerLevel() {
        return merLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.mer_Level
     *
     * @param merLevel the value for ks_payment_num.mer_Level
     *
     * @mbggenerated
     */
    public void setMerLevel(String merLevel) {
        this.merLevel = merLevel == null ? null : merLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.payment_Identity
     *
     * @return the value of ks_payment_num.payment_Identity
     *
     * @mbggenerated
     */
    public String getPaymentIdentity() {
        return paymentIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.payment_Identity
     *
     * @param paymentIdentity the value for ks_payment_num.payment_Identity
     *
     * @mbggenerated
     */
    public void setPaymentIdentity(String paymentIdentity) {
        this.paymentIdentity = paymentIdentity == null ? null : paymentIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.payment_Num
     *
     * @return the value of ks_payment_num.payment_Num
     *
     * @mbggenerated
     */
    public Long getPaymentNum() {
        return paymentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.payment_Num
     *
     * @param paymentNum the value for ks_payment_num.payment_Num
     *
     * @mbggenerated
     */
    public void setPaymentNum(Long paymentNum) {
        this.paymentNum = paymentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.fix_Reward
     *
     * @return the value of ks_payment_num.fix_Reward
     *
     * @mbggenerated
     */
    public Long getFixReward() {
        return fixReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.fix_Reward
     *
     * @param fixReward the value for ks_payment_num.fix_Reward
     *
     * @mbggenerated
     */
    public void setFixReward(Long fixReward) {
        this.fixReward = fixReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.subsidy
     *
     * @return the value of ks_payment_num.subsidy
     *
     * @mbggenerated
     */
    public Long getSubsidy() {
        return subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.subsidy
     *
     * @param subsidy the value for ks_payment_num.subsidy
     *
     * @mbggenerated
     */
    public void setSubsidy(Long subsidy) {
        this.subsidy = subsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.remarks
     *
     * @return the value of ks_payment_num.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.remarks
     *
     * @param remarks the value for ks_payment_num.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ks_payment_num.remarks_Two
     *
     * @return the value of ks_payment_num.remarks_Two
     *
     * @mbggenerated
     */
    public String getRemarksTwo() {
        return remarksTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ks_payment_num.remarks_Two
     *
     * @param remarksTwo the value for ks_payment_num.remarks_Two
     *
     * @mbggenerated
     */
    public void setRemarksTwo(String remarksTwo) {
        this.remarksTwo = remarksTwo == null ? null : remarksTwo.trim();
    }
}